force-app/demo/objects/Smart_Device_Event__e/Smart_Device_Event__e.object-meta.xml
<CustomObject>
    <description>An event that is send from a connected smart device</description>
    <label>Smart Device Event</label>
    <pluralLabel>Smart Device Events</pluralLabel>
</CustomObject>

force-app/demo/package/objects/Smart_Device_Event__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/demo/package/objects/Smart_Device_Event__e/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>The status of the smart device</description>
    <label>Status Code</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>Optional info for the reason of the status</description>
    <label>Status Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/package/objects/Smart_Device_Event_History__c/Smart_Device_Event_History__c.object-meta.xml
<CustomObject>
    <label>Smart Device Event History</label>
    <nameField>
        <displayFormat>EVT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Smart Device Event History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/demo/objects/Smart_Device_Event_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/package/objects/Smart_Device_Event_History__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/package/objects/Smart_Device_Event_History__c/fields/EventUuid__c.field-meta.xml
<CustomField>
    <fullName>EventUuid__c</fullName>
    <label>EventUuid</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event_History__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/demo/package/classes/SmartDeviceEventDemoLwcCtrl.cls
@SuppressWarnings('PMD.ApexDoc')
public with sharing class SmartDeviceEventDemoLwcCtrl {

    @AuraEnabled
    public static string createSmartEvent(String device, String action){
        try {
            // Create a new platform event
            EventBus.publish(new Smart_Device_Event__e(
                Action__c        = 'Switch State',
                Event_Date__c    = Date.today(),
                Device_Type__c   = Device,
                Status_Code__c   = (action == 'on') ? 1 : 0,
                Status_Reason__c = 'Switched device "'+device+'" to state "'+action+'"',
                Timestamp__c     = Datetime.now()
            ));

            // Return the success message
            return 'Successfully updated the state for device "'+device+'" to "'+action+'"';
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static void createHistoryRecordsFromEvent(Smart_Device_Event__e[] records){
        
        // This will create a copy in the local table so we can cross check
        Smart_Device_Event_History__c[] historyRecords = new Smart_Device_Event_History__c[]{};

        for(Smart_Device_Event__e record : records){
            historyRecords.add(new Smart_Device_Event_History__c(
                Action__c       = record.Action__c,
                Event_Date__c   = record.Event_Date__c,
                Device_Type__c  = record.Device_Type__c,
                Status_Code__c  = record.Status_Code__c,
                Status_Reason__c= record.Status_Reason__c,
                Timestamp__c    = record.Timestamp__c,
                EventUuid__c    = record.EventUuid,
                ReplayId__c     = record.ReplayId
            ));
        }
        insert historyRecords;
    }
}