force-app/demo/objects/Smart_Device_Event__e/Smart_Device_Event__e.object-meta.xml
<CustomObject>
    <description>An event that is send from a connected smart device</description>
    <label>Smart Device Event</label>
    <pluralLabel>Smart Device Events</pluralLabel>
</CustomObject>

force-app/demo/package/objects/Smart_Device_Event__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>The status of the smart device</description>
    <label>Status Code</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/demo/objects/Smart_Device_Event__e/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>Optional info for the reason of the status</description>
    <label>Status Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/demo/classes/SmartDeviceEventDemoLwcCtrl.cls
public with sharing class SmartDeviceEventDemoLwcCtrl {

    @AuraEnabled
    public static string createSmartEvent(String device, String action){
        try {
            // Create a new platform event
            EventBus.publish(new Smart_Device_Event__e(
                Action__c        = 'Switch State',
                Device_Type__c   = Device,
                Status_Code__c   = (action == 'on') ? 1 : 0,
                Status_Reason__c = 'Switched device "'+device+'" to state "'+action+'"',
                Timestamp__c     = Datetime.now()
            ));

            // Return the success message
            return 'Successfully updated the state for device "'+device+'" to "'+action+'"';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}